CREATE TABLE book (
                    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    title VARCHAR(200) NOT NUll UNIQUE,
                    author VARCHAR(100) NOT NULL ,
                    price INT NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP
);


INSERT INTO book (title, author, price) VALUES
                   ('Великий Гэтсби', 'Фрэнсис Скотт Фицджеральд', 800),
                   ('1984', 'Джордж Оруэлл', 600),
                   ('Убить пересмешника', 'Харпер Ли', 750),
                   ('Гордость и предубеждение', 'Джейн Остин', 700),
                   ('Моби Дик', 'Герман Мелвилл', 900),
                   ('451 градус по Фаренгейту', 'Рэй Брэдбери', 500),
                   ('Над пропастью во ржи', 'Джером Сэлинджер', 450),
                   ('Сияние', 'Стивен Кинг', 550),
                   ('Хоббит, или Туда и обратно', 'Дж. Р. Р. Толкин', 400),
                   ('Брave New World', 'Олдос Хаксли', 300);
