CREATE TABLE book (
                    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    title VARCHAR(200) NOT NUll UNIQUE,
                    author VARCHAR(100) NOT NULL ,
                    price INT NOT NULL,
                    description TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP
);


INSERT INTO book (title, author, price, description, created_at) VALUES
                    ('1984', 'Джордж Оруэлл', 500, 'Дистопический роман о тоталитарном будущем.', DEFAULT),
                    ('Гарри Поттер и философский камень', 'Джоан Роулинг', 600, 'Первая книга серии о Гарри Поттере.', DEFAULT),
                    ('Убить пересмешника', 'Харпер Ли', 450, 'Роман о расовых предрассудках в Америке.', DEFAULT),
                    ('Мастер и Маргарита', 'Михаил Булгаков', 700, 'Роман о любви и философии, пересекающийся с мифологией.', DEFAULT),
                    ('Преступление и наказание', 'Фёдор Достоевский', 550, 'Психологический роман о моральной ответственности.', DEFAULT);